#############
### THEME ###
#############
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "dirt", "sunrise"


#################
### HOME PAGE ###
#################
title: Jude Shin & Everything Else 
subtitle: everything about me # TODO: change this
description: Learn about my journey through Computer Science, Photography, Rock Climbing, and everything in between.
# head_scripts:
#   - https://code.jquery.com/jquery-3.2.1.min.js
#   - /assets/js/your-custom-head-script.js
 

###############
### GENERAL ###
###############
name: "Jude Shin"
url: "https://jude-shin.github.io" # TODO: change this when you choose a custom domain
baseurl: ""
# repository: "jude-shin/jude-shin" # author/repo-name 


################
### DEFAULTS ###
################
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # author_profile: true
      read_time: true
      show_date: true
      comments: false
      share: true
      related: true # TODO: what does this do?
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
#  # _foo (collections)
#  - scope:
#      path: ""
#      type: foo
#    values:
#      layout: single


############
### MISC ###
############
enable_copy_code_button: true
date_format: "%B %d, %Y"
timezone: America/Los_Angeles
search: true
lunr:
  search_within_pages: true

# # TODO: if this doesn't work, try version 2
# # paginate: 5
# pagination:
#   enabled: true
#   collection: 'posts'
#   per_page: 5
#   permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
#   title: ':title - page :num'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
#   trail:
#     before: 2
#     after: 2

include: ["_pages", "_posts"]

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

###################
### SITE AUTHOR ###
###################
author:
  name: "Jude Shin"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Passionate about Comuter Science, Climbing, Coaching, and Photography"
  location: "California"
  links: 
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/jude-shin"
    - label: "Github"
      icon: "fa-brands fa-square-github"
      url: "https://www.github.com/jude-shin"
    - label: "Instagram"
      icon: "fa-brands fa-square-instagram"
      url: "https://www.instagram.com/hey_jude_climbing"


##############
### FOOTER ###
##############
footer: 
  since: "2025"
  links: 
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/jude-shin"
    - label: "Github"
      icon: "fa-brands fa-square-github"
      url: "https://www.github.com/jude-shin"
    - label: "Instagram"
      icon: "fa-brands fa-square-instagram"
      url: "https://instagram.com/hey_jude_climbing"


###############
### PLUGINS ###
###############

# plugins:
# - jekyll-feed
